base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 10 
  username: root
  password: 
  socket: /tmp/mysql.sock

development:
  <<: *base
  database: ses_prod
test:
  <<: *base
  database: affabl_test
  
production:
  <<: *base
  database: ses_prod